version: 0.0
os: linux
files:
  - source: /
    destination: home/www
permissions:
  - object: home/www
    owner: ec2-user
    group: wheel
  AfterInstall:
    - location: script/AfterInstall.sh
      runas: ec2-user
  ApplicationStart:
    - location: script/ApplicationStart.sh
      runas: <root user>
