version: 1.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/www
permissions:
  - object: /home/ec2-user/www
    owner: ec2-user
    group: wheel
  - AfterInstall:
    - location: script/AfterInstall.sh
      runas: ec2-user
  - ApplicationStart:
    - location: script/ApplicationStart.sh
      runas: <root user>
